name: Build and Push Dev Image

on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ env.HOME }}/.kube/kubeconfig.yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image to dev
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker-registry.ebrains.eu
          docker build -t docker-registry.ebrains.eu/ebrains-data-curation/metadata-wizard-dev:${{ github.sha }} .
          docker push docker-registry.ebrains.eu/ebrains-data-curation/metadata-wizard-dev:${{ github.sha }}
      - name: Write kubeconfig to file
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/kubeconfig.yaml
      - name: Verify KUBECONFIG environment variable
        run: |
          echo "KUBECONFIG is set to: $KUBECONFIG"
          ls -l $KUBECONFIG
      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/metadata-wizard-dev container-0=docker-registry.ebrains.eu/ebrains-data-curation/metadata-wizard-dev:${{ github.sha }} --namespace=metadata-wizard-dev
